### PR TITLE
Add travis support and dartfmt...

### PR DESCRIPTION
**Pull request by matanlurey**
... similar to what has been done for [package:async](https://github.com/dart-lang/async/commit/bcbaeca7be91ee10e3a44ca7639ac65bb3b71845).

I'm hoping we can get this package more used and the community more aware of it by adding functionality such as that in https://github.com/dart-lang/core/issues/255, and that means having continuous integration :)

### CODE REVIEW

**Comment by matanlurey** [comment]
😮 Apparently I don't have write access and can't even assign reviewers, so...

@nex3 and @kevmoo, you're my only hope!

**Review by kevmoo — APPROVED** [review]
I enabled https://travis-ci.org/dart-lang/convert so we're ready to push...

**Comment by kevmoo** [comment]
...also fixed write access to this

**Comment by kevmoo** [comment]
Cool! https://travis-ci.org/dart-lang/convert/builds/233054104

**Pull request merged**
