### PR TITLE
Migrate to null safety

### PR DESCRIPTION
**Pull request by natebosch**

### CODE REVIEW

**Comment by natebosch** [comment]
Moving to the master branch. This package is in the allow list and is ready to be synced to the SDK.

**Review by stereotype441 — APPROVED** [review]
lgtm

**Comment by elansys-kc** [comment]
AFAICT decode can still return nulls. I was hoping to be able to avoid the code that many implement, replacing nulls with empty strings or placeholders. Will that be possible going forward either by default or a new decode method or function?

Gos JSON package takes a struct and only fills in the values, if they exist. That may be a possible alternative but with classes?

**Comment by natebosch** [comment]
> Will that be possible going forward either by default or a new decode method or function?

I don't understand the question.

`null` is a valid value to `encode` generally, so I would expect it to also be a valid value to decode. The recommendation is to use `??` to do the null defaulting.

Is there a particular API design you were hoping for?

**Comment by elansys-kc** [comment]
There may be many that would want nulls especially for existing code. My opinion is that using them is inferior as a bool or placeholder can always work and represents a certainty?. At least if you control the API. Logging any in that scenario is more useful.

The main point is that many of the Dart/Flutter JSON tutorials show replacing all NULLS before use. I just figured the convert package might save them a job, but then maybe it is better that people think about the details...not sure?

**Comment by natebosch** [comment]
> maybe it is better that people think about the details

I think it's probably true that this detail is best handled by the caller.

I'm not sure what the API would look like to avoid that.

**Pull request merged**
