### PR TITLE
Update SDK constraint to 2.12.0-0

### PR DESCRIPTION
**Pull request by kevmoo**
Update dependencies and travis config

### CODE REVIEW

**Comment by jakemac53** [comment]
This looks like it was already partially merged to me? Not sure what is going on exactly here.

**Comment by kevmoo** [comment]
> This looks like it was already partially merged to me? Not sure what is going on exactly here.

Yup. I had a null safe branch locally. I can rebase if you like.

**Comment by jakemac53** [comment]
I am mostly confused by the pull request description which doesn't seem accurate?

**Comment by kevmoo** [comment]
PTAL

**Comment by kevmoo** [comment]
@jakemac53 – should I just prepare this for publish?

**Comment by jakemac53** [comment]
cc @natebosch do you have anything you want to do on this package before we release it?

**Review by jakemac53 — APPROVED** [review]

**Comment by natebosch** [comment]
It looks like we need to bump the major version.

**Pull request merged**
